######################################################################
# Automatically generated by qmake (3.0) Mon Jan 29 03:25:25 2018
######################################################################

TEMPLATE = app
TARGET = qt5-keypad
INCLUDEPATH += .

# Input
HEADERS += win.h
SOURCES += qt5-keypad.cpp win.cpp

QT += widgets

